
services:
  php:
    container_name: setup-php-subwaysurf
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/consf.d/local.ini
    networks:
      - network-subwaysurf

  nginx:
    container_name: setup-nginx-subwaysurf
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network-subwaysurf

  mysql:
    container_name: setup-mysql-subwaysurf
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - data-subwaysurf:/var/lib/mysql/
   
    networks:
      - network-subwaysurf
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}


  phpmyadmin:
    container_name: setup-phpmyadmin-subwaysurf
    image: phpmyadmin:5.2
    restart: always
    ports:
      - '8888:80'
    networks:
      - network-subwaysurf
    environment:
      PMA_HOST: setup-mysql-subwaysurf
    depends_on:
      - mysql

  redis:
    container_name: setup-redis-subwaysurf
    image: redis:latest
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - '6379:6379'
    networks:
      - network-subwaysurf

networks:
  network-subwaysurf:
    driver: bridge


volumes:
  data-subwaysurf:
    driver: local
